"""
Little Princesses ERP - Master Action Map
Maps all frontend/API action strings to their respective domain handler functions.
"""

from . import (
    pg_quality, pg_auth, pg_customers, pg_products,
    pg_inventory, pg_orders, pg_purchases, pg_suppliers,
    pg_vouchers, pg_expenses, pg_accounts, pg_journal,
    pg_factory, pg_payroll, pg_system, pg_audit,
    pg_dashboard, pg_customer_tracking, pg_warehouses,
    pg_receipt_sync
)

ACTION_HANDLERS = {
    # الجودة والمطابقة
    "getQualitySummary": pg_quality.get_quality_summary,
    "getQualityDashboard": pg_quality.get_quality_dashboard_pg,
    "getQualityInspections": pg_quality.get_quality_inspections,
    "addQualityInspection": pg_quality.add_quality_inspection,
    "getQualityDefects": pg_quality.get_quality_defects,
    "addQualityDefect": pg_quality.add_quality_defect,
    "getFeedback": pg_quality.get_quality_feedback,
    "getQualityFeedback": pg_quality.get_quality_feedback,
    "addFeedback": pg_quality.add_quality_feedback,
    "addQualityFeedback": pg_quality.add_quality_feedback,
    "getQualityComplaints": pg_quality.get_quality_complaints,
    "addQualityComplaint": pg_quality.add_quality_complaint,
    "getQualityReturns": pg_quality.get_quality_returns,
    "addQualityReturn": pg_quality.add_quality_return,
    "getQualityActions": pg_quality.get_quality_actions,
    "addQualityAction": pg_quality.add_quality_action,
    "getQualityCorrectiveActions": pg_quality.get_quality_actions,
    "addQualityCorrectiveAction": pg_quality.add_quality_action,
    "getQualityCheckpoints": pg_quality.get_quality_checkpoints,
    "saveQualityCheckpoint": pg_quality.save_quality_checkpoint,
    "getQualitySettings": pg_quality.get_quality_settings,
    "saveQualitySettings": pg_quality.save_quality_settings,

    # المستخدمين والعملاء
    "getUsers": pg_auth.get_users_pg,
    "saveUser": pg_auth.sync_user_to_pg,
    "addUser": pg_auth.sync_user_to_pg,
    "getCustomers": pg_customers.get_customers,
    "addCustomer": pg_customers.add_customer,
    "updateCustomer": pg_customers.add_customer,
    "deleteCustomer": pg_customers.delete_customer,

    # المنتجات والمخزون
    "getProducts": pg_products.get_products,
    "addProduct": pg_products.add_product,
    "updateProduct": pg_products.add_product,
    "deleteProduct": pg_products.delete_product,
    "getBOM": pg_products.get_bom_models,
    "getBOMModels": pg_products.get_bom_models,
    "saveBOM": pg_products.save_bom_model,
    "saveBOMModel": pg_products.save_bom_model,
    "deleteBOM": pg_products.delete_bom_model,
    "deleteBOMModel": pg_products.delete_bom_model,
    "getInventory": pg_inventory.get_inventory,
    "addInventory": pg_inventory.add_or_update_inventory,
    "addOrUpdateItem": pg_inventory.add_or_update_inventory,
    "updateInventoryQty": pg_inventory.update_inventory_qty,
    "adjustInventory": pg_inventory.adjust_inventory,
    "adjust_inventory": pg_inventory.adjust_inventory,
    "issueMaterials": pg_inventory.update_inventory_qty,
    "recordInventoryMovement": pg_inventory.update_inventory_qty,
    "deleteInventory": pg_inventory.delete_inventory,
    "deleteItem": pg_inventory.delete_inventory,
    "getWarehouses": pg_warehouses.get_warehouses,
    "addWarehouse": pg_warehouses.add_warehouse,
    "createWarehouse": pg_warehouses.add_warehouse,
    "transferStock": pg_warehouses.transfer_warehouse_stock,
    "transferWarehouseStock": pg_warehouses.transfer_warehouse_stock,
    "getItemStockByWarehouse": lambda p: pg_warehouses.get_item_stock_by_warehouse(p.get("item_id") or p.get("id")),

    # المبيعات والمشتريات والموردين
    "getOrders": pg_orders.get_orders,
    "addOrder": pg_orders.add_order,
    "createOrder": pg_orders.add_order,
    "updateOrder": pg_orders.update_order,
    "deleteOrder": pg_orders.delete_order,
    "getPurchases": pg_purchases.get_purchases,
    "addPurchase": pg_purchases.add_purchase,
    "addPurchaseInvoice": pg_purchases.add_purchase,
    "updatePurchase": pg_purchases.add_purchase,
    "deletePurchase": pg_purchases.delete_purchase,
    "removePurchase": pg_purchases.delete_purchase,
    "purgePurchasesSheetData": pg_purchases.purge_purchases,
    "getSuppliers": pg_suppliers.get_suppliers,
    "addSupplier": pg_suppliers.add_supplier,
    "updateSupplier": pg_suppliers.add_supplier,
    "deleteSupplier": pg_suppliers.delete_supplier,

    # الحسابات والمالية
    "getVouchers": pg_vouchers.get_vouchers,
    "getPayments": pg_vouchers.get_vouchers,
    "addVoucher": pg_vouchers.add_voucher,
    "addPayment": pg_vouchers.add_voucher,
    "updateVoucher": pg_vouchers.add_voucher,
    "deleteVoucher": pg_vouchers.delete_voucher,
    "deletePayment": pg_vouchers.delete_voucher,
    "recalculateAdvanceDeposits": pg_receipt_sync.recalculate_advance_deposits_action,
    "getExpenses": pg_expenses.get_expenses,
    "addExpense": pg_expenses.add_expense,
    "deleteExpense": pg_expenses.delete_expense,
    "removeExpense": pg_expenses.delete_expense,
    "getAccounts": pg_accounts.get_accounts,
    "getChartOfAccounts": pg_accounts.get_accounts,
    "getChartOfAccountsTree": pg_accounts.get_accounts,
    "addAccount": pg_accounts.add_account,
    "saveAccount": pg_accounts.add_account,
    "deleteAccount": pg_accounts.delete_account,
    "resetCleanChartOfAccounts": pg_accounts.reset_clean_chart_of_accounts,
    "getJournalEntries": pg_journal.get_journal_entries,
    "addJournalEntry": pg_journal.add_journal_entry,
    "saveJournalEntry": pg_journal.add_journal_entry,
    "updateJournalEntry": pg_journal.add_journal_entry,
    "deleteJournalEntry": pg_journal.delete_journal_entry,
    "getCurrencies": pg_accounts.get_currencies,
    "updateExchangeRate": pg_accounts.update_exchange_rate,

    # المعمل والتشغيل
    "getFactory": pg_factory.get_factory,
    "updateFactory": pg_factory.update_factory,
    "deleteFactoryOrder": pg_factory.delete_factory_order,
    "deleteProductionOrder": pg_factory.delete_factory_order,
    "processStockInflow": pg_factory.process_stock_inflow,
    "reverseStockInflow": pg_factory.reverse_stock_inflow,
    "deliverAndSettleOrder": pg_factory.deliver_and_settle_order,
    "reverseOrderDelivery": pg_factory.reverse_order_delivery,
    "getFactoryAnalytics": pg_factory.get_factory_analytics,
    "getTailorCommissions": pg_factory.get_tailor_commissions,
    "getTailorPayoutSummary": pg_factory.get_tailor_payout_summary,
    "getTailorUnpaidPieces": pg_factory.get_tailor_unpaid_pieces,
    "postTailorPayoutVoucher": pg_factory.post_tailor_payout_voucher,
    "getTailorPayoutVouchers": pg_factory.get_tailor_payout_vouchers,

    # الموارد البشرية والرواتب
    "getEmployees": pg_payroll.get_employees,
    "addEmployee": pg_payroll.add_employee,
    "updateEmployee": pg_payroll.add_employee,
    "deleteEmployee": pg_payroll.delete_employee,
    "getPayroll": pg_payroll.get_payroll,
    "addPayrollBatch": pg_payroll.add_payroll_batch,
    "updatePayrollRecord": pg_payroll.update_payroll_record,
    "addAdvance": pg_payroll.add_advance,
    "postPayroll": pg_payroll.post_payroll,
    "paySalary": pg_payroll.post_payroll,
    "calculatePayroll": pg_payroll.calculate_payroll,

    # النظام والتدقيق والنسخ الاحتياطي
    "clearAllData": pg_system.clear_all_transactional_data,
    "clearAllTransactionalData": pg_system.clear_all_transactional_data,
    "wipeAllData": pg_system.clear_all_transactional_data,
    "getSettings": pg_system.get_system_settings,
    "getSystemSettings": pg_system.get_system_settings,
    "saveSettings": pg_system.save_system_settings,
    "saveSystemSettings": pg_system.save_system_settings,
    "getAuditLogs": pg_audit.get_audit_logs,
    "addAuditLog": pg_audit.add_audit_log,
    "getBackupStatus": pg_system.get_backup_status,
    "createSnapshot": pg_system.create_backup_snapshot,
    "createBackupSnapshot": pg_system.create_backup_snapshot,
    "restoreBackup": pg_system.restore_backup_data,
    "restoreBackupData": pg_system.restore_backup_data,
    "getDashboardStats": pg_dashboard.get_dashboard_stats,

    # التتبع والبروفات
    "getCustomerOrderTracking": lambda p: pg_customer_tracking.get_customer_order_tracking(p.get("order") or p.get("order_id") or p.get("id") or p.get("order_no")),
    "confirmCustomerFitting": lambda p: pg_customer_tracking.confirm_customer_fitting(p.get("order") or p.get("order_id") or p.get("id") or p.get("order_no"), p.get("notes", "")),
    "submitTailorStage": pg_factory.submit_tailor_stage_completion,
    "getFittingAlterations": pg_factory.get_fitting_alterations,
    "addFittingAlteration": pg_factory.add_fitting_alteration,
    "updateFittingAlterationStatus": pg_factory.update_fitting_alteration_status,
    "getAtelierWatchdog": pg_factory.get_atelier_watchdog,
    "scanToDeliverOrder": pg_factory.scan_to_deliver_order,
}
